services:
  ecg-rt:
    build: .
    container_name: ecg-rt
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - TORCH_NUM_THREADS=2
    restart: unless-stopped
